# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-License-Identifier: MIT

# Has configurations that affect what and how we release stuff.
# Needed since our products differ in little things

# - signed_release
#   Says if we currently upload a signed asset to GH releases. Some of our projects
#   still don't, but will.
# - automated_3rdparty_updates
#   Says if we've automated github actions to update 3rdparty and create PR. Eventually
#   we'd like all repos with 3rdparty to have this.
# - has_submodules
#   Repos with submodules need to have their submodules in the release tarball, and should
#   be subject to automated submodule bump.
# - has_fetchcontent
#   Same purpose as 'has_submodules'
# - homebrew
#   Points to the homebrew formula. consumed by our KDAB/homebrew-tap scripts
# - tag_prefix
#   Some projects have tags prefixed with their name, for example tag 'kdsoap-x.y.z', others prefixed
#   with 'v'. We can't normalized this now, as it would break package urls.
# - tarball_includes_submodules
#   Default false.
#   Whether the release tarball includes the submodules. This is the case for submodules which are
#   unpopular and not packaged elsewhere.

[project]

[project.KDSoap]
signed_release = true
has_submodules = true
tarball_includes_submodules = true
has_fetchcontent = false
automated_3rdparty_updates = false
tag_prefix = "kdsoap-"
homebrew = ["kdsoap-qt5.rb", "kdsoap-qt6.rb"]
main_branch = "master"

[project.KDSoap.dependencies]
[project.KDSoap.dependencies.libkode]
# libkode has no tags
# submodule = "kdwsdl2cpp/libkode"

[project.KDReports]
signed_release = true
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
tag_prefix = "kdreports-"
homebrew = ["kdreports-qt5.rb", "kdreports-qt6.rb"]
main_branch = "master"

[project.KDDockWidgets]
tag_prefix = "v"
signed_release = true
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = true
homebrew = ["kddockwidgets-qt5.rb", "kddockwidgets-qt6.rb"]
main_branch = "main"
has_version_txt = true

[project.KDStateMachineEditor]
tag_prefix = "v"
signed_release = true
has_submodules = true
has_fetchcontent = false
automated_3rdparty_updates = false
main_branch = "master"
homebrew = ["kdstatemachineeditor-qt5.rb", "kdstatemachineeditor-qt6.rb"]

[project.KDStateMachineEditor.dependencies]
[project.KDStateMachineEditor.dependencies.graphviz]
has_github_release = false # it's in gitlab

submodule = "3rdparty/graphviz"
[project.KDSingleApplication]
tag_prefix = "v"
signed_release = true
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdsingleapplication-qt5.rb", "kdsingleapplication-qt6.rb"]
main_branch = "master"

[project.GammaRay]
tag_prefix = "v"
signed_release = true
has_submodules = true
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["gammaray-qt5.rb", "gammaray-qt6.rb"]
main_branch = "master"

[project.GammaRay.dependencies]
[project.GammaRay.dependencies.KDStateMachineEditor]
submodule = "3rdparty/KDStateMachineEditor"


[project.KDChart]
tag_prefix = "v"
signed_release = true
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdchart-qt5.rb", "kdchart-qt6.rb"]
main_branch = "master"

[project.KDBindings]
tag_prefix = "v"
signed_release = false
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdbindings.rb"]
main_branch = "main"

[project.KDAlgorithms]
tag_prefix = ""
signed_release = false
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdalgorithms.rb"]
main_branch = "main"

[project.KDUtils]
tag_prefix = "v"
signed_release = false
has_submodules = false
has_fetchcontent = true
automated_3rdparty_updates = false
homebrew = ["kdutils.rb"]
main_branch = "main"

[project.Knut]
has_version_txt = true

tag_prefix = "v"
signed_release = true
has_submodules = true
has_fetchcontent = false
automated_3rdparty_updates = false
main_branch = "main"
[project.Knut.dependencies]
[project.Knut.dependencies.extra_cmake_modules]
submodule = "3rdparty/extra-cmake-modules"
has_github_release = false
main_branch = 'master'

[project.Knut.dependencies.kdalgorithms]
submodule = "3rdparty/kdalgorithms"

[project.Knut.dependencies.ksyntaxhighlighting]
submodule = "3rdparty/ksyntaxhighlighting"
has_github_release = false
main_branch = 'master'

[project.Knut.dependencies.nlohmann_json]
submodule = "3rdparty/nlohmann-json"

[project.Knut.dependencies.pugixml]
submodule = "3rdparty/pugixml"

[project.Knut.dependencies.spdlog]
submodule = "3rdparty/spdlog"

[project.Knut.dependencies.tree_sitter]
submodule = "3rdparty/tree-sitter"

[project.Knut.dependencies.tree_sitter_cpp]
submodule = "3rdparty/tree-sitter-cpp"

[project.Knut.dependencies.tree_sitter_qmljs]
submodule = "3rdparty/tree-sitter-qmljs"
has_github_release = false
main_branch = 'master'

[project.hotspot]
tag_prefix = "v"
has_submodules = true
has_fetchcontent = false
automated_3rdparty_updates = false
main_branch = "master"

# we probably don't want to manage hotspot dependencies automatically
# [project.hotspot.dependencies.PrefixTickLabels]
# # submodule = "3rdparty/PrefixTickLabels" no releases
# has_github_release = false
# main_branch = 'master'

# [project.hotspot.dependencies.perfparser]
# submodule = "3rdparty/perfparser"
# has_github_release = false
# main_branch = 'hotspot'
