# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-License-Identifier: MIT

# Has configurations that affect what and how we release stuff.
# Needed since our products differ in little things

# - signed_release
#   Says if we currently upload a signed asset to GH releases. Some of our projects
#   still don't, but will.
# - automated_3rdparty_updates
#   Says if we've automated github actions to update 3rdparty and create PR. Eventually
#   we'd like all repos with 3rdparty to have this.
# - has_submodules
#   Repos with submodules need to have their submodules in the release tarball, and should
#   be subject to automated submodule bump.
# - has_fetchcontent
#   Same purpose as 'has_submodules'
#
# - homebrew
#   Points to the homebrew formula. consumed by our KDAB/homebrew-tap scripts


[project]

[project.KDSoap]
signed_release = true
has_submodules = true
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdsoap-qt5.rb", "kdsoap-qt6.rb"]

[project.KDReports]
signed_release = true
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdreports-qt5.rb", "kdreports-qt6.rb"]

[project.KDDockWidgets]
signed_release = true
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = true
homebrew = ["kddockwidgets-qt5.rb", "kddockwidgets-qt6.rb"]

[project.KDStateMachineEditor]
signed_release = true
has_submodules = true
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdstatemachineeditor-qt5.rb", "kdstatemachineeditor-qt6.rb"]

[project.KDSingleApplication]
signed_release = true
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdsingleapplication-qt5.rb", "kdsingleapplication-qt6.rb"]

[project.Gammaray]
signed_release = true
has_submodules = true
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["gammaray-qt5.rb", "gammaray-qt6.rb"]

[project.KDBindings]
signed_release = false
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdbindings.rb"]

[project.KDAlgorithms]
signed_release = false
has_submodules = false
has_fetchcontent = false
automated_3rdparty_updates = false
homebrew = ["kdalgorithms.rb"]

[project.KDUtils]
signed_release = false
has_submodules = false
has_fetchcontent = true
automated_3rdparty_updates = false
homebrew = ["kdutils.rb"]
