# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-License-Identifier: MIT

# Has configurations that affect what and how we release stuff.
# Needed since our products differ in little things

# - signed_release
#   Says if we currently upload a signed asset to GH releases. Some of our projects
#   still don't, but will.
# - homebrew
#   Points to the homebrew formula. consumed by our KDAB/homebrew-tap scripts
# - tag_prefix
#   Some projects have tags prefixed with their name, for example tag 'kdsoap-x.y.z', others prefixed
#   with 'v'. We can't normalized this now, as it would break package urls.
# - tarball_includes_submodules
#   Default false.
#   Whether the release tarball includes the submodules. This is the case for submodules which are
#   unpopular and not packaged elsewhere.

[project]

[project.KDSoap]
signed_release = true
tarball_includes_submodules = true
tag_prefix = "kdsoap-"
homebrew = ["kdsoap-qt5.rb", "kdsoap-qt6.rb"]
main_branch = "master"

[project.KDSoap.dependencies]
[project.KDSoap.dependencies.libkode]
# libkode has no tags
# submodule = "kdwsdl2cpp/libkode"

[project.KDReports]
signed_release = true
tag_prefix = "kdreports-"
homebrew = ["kdreports-qt5.rb", "kdreports-qt6.rb"]
main_branch = "master"

[project.KDDockWidgets]
tag_prefix = "v"
signed_release = true
homebrew = ["kddockwidgets-qt5.rb", "kddockwidgets-qt6.rb"]
main_branch = "main"
has_version_txt = true

[project.KDStateMachineEditor]
tag_prefix = "v"
signed_release = true
main_branch = "master"
homebrew = ["kdstatemachineeditor-qt5.rb", "kdstatemachineeditor-qt6.rb"]

[project.KDStateMachineEditor.dependencies]
[project.KDStateMachineEditor.dependencies.graphviz]
submodule = "3rdparty/graphviz"

[project.KDSingleApplication]
tag_prefix = "v"
signed_release = true
homebrew = ["kdsingleapplication-qt5.rb", "kdsingleapplication-qt6.rb"]
main_branch = "master"

[project.GammaRay]
tag_prefix = "v"
signed_release = true
homebrew = ["gammaray-qt5.rb", "gammaray-qt6.rb"]
main_branch = "master"

[project.GammaRay.dependencies]
[project.GammaRay.dependencies.KDStateMachineEditor]
submodule = "3rdparty/KDStateMachineEditor"


[project.KDChart]
tag_prefix = "v"
signed_release = true
homebrew = ["kdchart-qt5.rb", "kdchart-qt6.rb"]
main_branch = "master"

[project.KDBindings]
tag_prefix = "v"
signed_release = false
homebrew = ["kdbindings.rb"]
main_branch = "main"

[project.KDAlgorithms]
tag_prefix = ""
signed_release = false
homebrew = ["kdalgorithms.rb"]
main_branch = "main"

[project.KDUtils]
tag_prefix = "v"
signed_release = false
homebrew = ["kdutils.rb"]
main_branch = "main"

[project.KDUtils.dependencies.KDBindings]
fetchcontent_path = "cmake/dependencies.cmake"
main_branch = "main"

[project.KDUtils.dependencies.fmt]
fetchcontent_path = "cmake/dependencies.cmake"
main_branch = "master"

[project.KDUtils.dependencies.spdlog]
fetchcontent_path = "cmake/dependencies.cmake"
main_branch = "v1.x"

[project.KDUtils.dependencies.whereami]
fetchcontent_path = "cmake/dependencies.cmake"
main_branch = "master"

[project.KDUtils.dependencies.mio]
fetchcontent_path = "cmake/dependencies.cmake"
main_branch = "master"

[project.KDUtils.dependencies.doctest]
fetchcontent_path = "tests/CMakeLists.txt"
main_branch = "master"

[project.Knut]
has_version_txt = true

tag_prefix = "v"
signed_release = true
main_branch = "main"
[project.Knut.dependencies]
[project.Knut.dependencies.extra_cmake_modules]
submodule_path = "3rdparty/extra-cmake-modules"
main_branch = 'master'

[project.Knut.dependencies.kdalgorithms]
submodule_path = "3rdparty/kdalgorithms"

[project.Knut.dependencies.ksyntaxhighlighting]
submodule_path = "3rdparty/ksyntaxhighlighting"
main_branch = 'master'

[project.Knut.dependencies.nlohmann_json]
submodule_path = "3rdparty/nlohmann-json"
main_branch = 'master'

[project.Knut.dependencies.pugixml]
submodule_path = "3rdparty/pugixml"
main_branch = 'master'

[project.Knut.dependencies.spdlog]
submodule_path = "3rdparty/spdlog"
main_branch = 'v1.x'

[project.Knut.dependencies.tree_sitter]
submodule_path = "3rdparty/tree-sitter"
main_branch = 'master'

[project.Knut.dependencies.tree_sitter_cpp]
submodule_path = "3rdparty/tree-sitter-cpp"
main_branch = 'master'

[project.Knut.dependencies.tree_sitter_qmljs]
submodule_path = "3rdparty/tree-sitter-qmljs"
main_branch = 'master'

[project.hotspot]
tag_prefix = "v"
main_branch = "master"

# we probably don't want to manage hotspot dependencies automatically
# [project.hotspot.dependencies.PrefixTickLabels]
# # submodule_path = "3rdparty/PrefixTickLabels" no releases
# main_branch = 'master'

# [project.hotspot.dependencies.perfparser]
# submodule_path = "3rdparty/perfparser"
# main_branch = 'hotspot'
