# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
# SPDX-License-Identifier: MIT

name: Test scripts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: fetch test submodules
        run: |
          cd tests/submodules/knut
          git submodule update --init --force --recursive -- 3rdparty/*

      - name: Run gh_utils test
        run: python src/gh_utils.py --get-latest-release=KDAB/KDDockWidgets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pytest tests
        run: |
          pip install pytest
          pytest
